# Travis file
# See https://docs.travis-ci.com/user/languages/r/

language: r
cache: packages

r_packages:
  - covr

apt_packages:
  - libgit2-dev

after_success:
  - Rscript -e 'library(covr); codecov()'
